name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with :
        submodules: true
    - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libbsd-dev libxext-dev libx11-dev
    - name: Compiling using GCC
      run: make re
      env:
        CC: gcc

    - name: Compiling using Clang
      run: make re
      env:
        CC: clang